
apiVersion: v1
kind: Template
metadata:
  name: build-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${TAG}
    runPolicy: Serial
    source:
      type: Git
      contextDir: ${GIT_DIR}
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
           kind: ImageStreamTag
           namespace: openshift
           name: 's2i-java:latest'



parameters:
- description: The name of the service
  displayName: Name
  name: NAME
  required: true
  value: todo-service
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: GIT_URL
  required: true
  value: https://github.com/steven166/openshift-example
- description: Branch or Tag in the Repository to checkout
  displayName: Git Branch or Tag
  name: GIT_REF
  required: true
  value: master
- description: SubFolder inside git to build
  displayName: SubFolder
  name: GIT_DIR
  required: true
  value: .
