
apiVersion: v1
kind: Template
metadata:
  name: build-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${TAG}
    runPolicy: Serial
    source:
      type: Git
      contextDir: ${GIT_DIR}
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
           kind: ImageStreamTag
           namespace: openshift
           name: 's2i-java:latest'



parameters:
- description: Name
  name: NAME
  required: true
- description: The image tag.
  name: TAG
  required: true
  value: dev
